tasks:
  - init: >
      docker compose pull
  - name: finish
    init: |
      gp await-port 7000
      python -m pip install --upgrade pip
  - command: |
      docker compose up -d
      pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - formulahendry.code-runner
    - ms-toolsai.jupyter-keymap
